export const penelope_video = {
    name: "蓝色小考拉",
    nameEn: "penelope",
    default_url: "//player.bilibili.com/player.html?aid=248463989&bvid=BV11v411V75C&danmaku=false&muted=false&autoplay=true&p=",
    videoList: [
        {"id": 1, "name": "gets_dressed_all_by_herself"},
        {"id": 2, "name": "at_school"},
        {"id": 3, "name": "has_a_bath"},
        {"id": 4, "name": "makes_sketches"},
        {"id": 5, "name": "plants_a_seed"},
        {"id": 6, "name": "rides_a_bike"},
        {"id": 7, "name": "feeds_the_Animals"},
        {"id": 8, "name": "goes_shopping"},
        {"id": 9, "name": "in_the_snow"},
        {"id": 10, "name": "opens_a_shop"},
        {"id": 11, "name": "goes_to_the_beach"},
        {"id": 12, "name": "play_at_teh_seaside"},
        {"id": 13, "name": "Penelope_Is_Polite"},
        {"id": 14, "name": "Playing_With_Colours"},
        {"id": 15, "name": "Penelope_Sings"},
        {"id": 16, "name": "Penelope_Its_Delicious"},
        {"id": 17, "name": "Penelope_Tidies_Her_Room"},
        {"id": 18, "name": "Hide_and_Seek"},
        {"id": 19, "name": "Grandpas_Birthday"},
        {"id": 20, "name": "Penelope_Makes_Biscuits"},
        {"id": 21, "name": "Milo_and_Madeline"},
        {"id": 22, "name": "Penelope_Takes_a_Nap"},
        {"id": 23, "name": "School_Carnival"},
        {"id": 24, "name": "Christmas_Present"},
        {"id": 25, "name": "School_Trip"},
        {"id": 26, "name": "Merry_Christmas_Penelope"},
        {"id": 27, "name": "Christmas_Party"},
        {"id": 28, "name": "Lets_Close_The_Door_Penelope"},
        {"id": 29, "name": "Learns_About_Different_Shapes"},
        {"id": 30, "name": "Lets_Hold_Hands_Penelope"},
        {"id": 31, "name": "Penelope_Builds_a_Birdhouse"},
        {"id": 32, "name": "Penelope_Goes_Skating"},
        {"id": 33, "name": "Penelope_Names_Some_Piglets"},
        {"id": 34, "name": "Penelopes_Sweet_Dream_Book"},
        {"id": 35, "name": "Happy_Halloween"},
        {"id": 36, "name": "Penelopes_Museum"},
        {"id": 37, "name": "Fun_In_the_Weather"},
        {"id": 38, "name": "Penelopes_Family_Concert"},
        {"id": 39, "name": "Penelope_Goes_Fishing_With_Grandpa"},
        {"id": 40, "name": "The_Autumn_Harvest_Party"},
        {"id": 41, "name": "Penelope_Helps_Dad"},
        {"id": 42, "name": "Penelope_Catches_Cold"},
        {"id": 43, "name": "Penelope_Goes_Into_Town"},
        {"id": 44, "name": "Penelope_Exchanges_Some_Letters"},
        {"id": 45, "name": "In_The_Summertime"},
        {"id": 46, "name": "Mums_Birthday"},
        {"id": 47, "name": "Penelope_at_the_Pool"}
    ]
}

export const gigantosaurus_video = {
    name: "小恐龙大冒险",
    nameEn: "gigantosaurus",
    default_url: "//player.bilibili.com/player.html?aid=699548502&bvid=BV1om4y1i7fU&danmaku=false&muted=false&autoplay=true&p=",
    videoList:[
        {"id":1,"name":"Mazu Takes A Chance"},
        {"id":2,"name":"Rock Out"},
        {"id":3,"name":"The Crevice"},
        {"id":4,"name":"Don't Cave In"},
        {"id":5,"name":"The Lost Egg"},
        {"id":6,"name":"Saving Ayati"},
        {"id":7,"name":"The Lost Egg"},
        {"id":8,"name":"The Lost Egg"},
        {"id":9,"name":"The Imitator"},
        {"id":10,"name":"The Lost Egg"},
        {"id":11,"name":"The Biggest Hero"},
        {"id":12,"name":"Think Quick"},
        {"id":13,"name":"No Joke"},
        {"id":14,"name":"Please Don't Pick The Flowers"},
        {"id":15,"name":"Frozen Giganto"},
        {"id":16,"name":"Seeing Stars"},
        {"id":17,"name":"Treasure"},
        {"id":18,"name":"Giganto's Laugh"},
        {"id":19,"name":"Talent-O-Saurus"},
        {"id":20,"name":"Mash The Raptor"},
        {"id":21,"name":"Invisi-Bill"},
        {"id":22,"name":"Dinosia"},
        {"id":23,"name":"Differing Dino Tales"},
        {"id":24,"name":"Big Bill"},
        {"id":25,"name":"A Very Sticky Problem"},
        {"id":26,"name":"The Shortest Day"},
        {"id":27,"name":"The Best Crest"},
        {"id":28,"name":"The Big Mean Green"},
        {"id":29,"name":"Pathy Sees The Light"},
        {"id":30,"name":"Bill's Night Feast"},
        {"id":31,"name":"Forward Marsh"},
        {"id":32,"name":"Racing Gigant"},
        {"id":33,"name":"The Drought"},
        {"id":34,"name":"The Challenge"},
        {"id":35,"name":"Giganto's Boss"},
        {"id":36,"name":"Follow The Leader"},
        {"id":37,"name":"Bill's Broken Promise"},
        {"id":38,"name":"Crying Wolfasaurus"},
        {"id":39,"name":"A Tiny Favor"},
        {"id":40,"name":"The Floating Stone"},
        {"id":41,"name":"How Giganto Got His Roar"},
        {"id":42,"name":"An Artist Is Born"},
        {"id":43,"name":"Born Tree"},
        {"id":44,"name":"A Giganto Power"},
        {"id":45,"name":"A light In The Storm"},
        {"id":46,"name":"Coco Bill"},
        {"id":47,"name":"Brothers And Sisters"},
        {"id":48,"name":"Mazu's Comet"},
        {"id":49,"name":"Good Bye Giganto! Part 1"},
        {"id":50,"name":"Good Bye Giganto! Part 2"}
    ]

}
